### ISSUE TITLE
Decide correct Swift types for user-provided data

### ISSUE THREAD

**Issue by lawrence-forooghian** [ably/ably-chat-swift#13]
I am not sure of the best way to represent the following types from the TypeScript repo in Swift:

- [x] `export type Metadata = Record<string, unknown>;` — I’m assuming that in reality there are some restrictions on this `unknown` — done in #202 
- [x] `export type PresenceData = unknown; // Any JSON serializable data type.` — Swift doesn’t have a good type for this, but see an example of how to create a fluent one on https://www.douggregor.net/posts/swift-for-cxx-practitioners-literals/ — done in #189 
- [x] `PresenceMember`’s `extras: any;` — Again, I imagine there are in reality some restrictions — done in #201 

Given the emphasis on type safety in Swift, we want to do our best to make the type system:

* only permit valid values
* require as little runtime type-checking as possible for users, and guide the user as much as possible to get this type-checking right

May be worth thinking about whether `Codable` could be of any use.

As part of this it might also be worth:

- [x] revisiting how I’ve chosen to implement the `Headers` type in Swift.

┆Issue is synchronized with this [Jira Story](https://ably.atlassian.net/browse/ECO-4927) by [Unito](https://www.unito.io)

**Comment by umair-ably** [comment]
Extending this to cover the change to Int from NSNumber in both Metadata and Headers. They both need to conform to Codable due to being using in another Codable conforming type (`Message`). Changing NSNumber to Int was the easiest way to resolve this right now, but unsure what ramifications (if any) there are from doing this.
